name: C++ CI

on:
  push:
    branches: [ "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        compiler: [g++, clang]
      

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Configure Project
        uses: threeal/cmake-action@v1.3.0
        with:
          generator: Ninja
          cxx-compiler: ${{ matrix.compiler }}
          options:
            CMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build Project
        run: |
          ${{ matrix.compiler }} --version
          cmake --build build

      - name: Test Project
        run: ctest --test-dir build
